services:
  owl-backend:
    hostname: owl-backend
    image: athenadecisionsystems/athena-owl-backend:1.0.0
    container_name: owl-backend
    ports:
      - 8002:8000
    environment:
      CONFIG_FILE: /app/config/config.yaml
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ../../.env:/app/.env
      - ./data/:/app/data
      - ./src:/app/myowl
  ollama:
    image: ollama/ollama
    hostname: ollama
    volumes:
        - ./start-ollama.sh:/start-ollama.sh
    container_name: ollama
    entrypoint: ["/usr/bin/bash", "/start-ollama.sh"]
    ports:
        - 11434:11434