site_name: Machine Learning Studies
repo_url: https://github.com/jbcodeforce/ML-studies
nav:
  - Introduction: index.md
  - Concepts: 
    - Math summary: concepts/maths.md
  - Data management:
    - Introduction: data/index.md
    - Feature Engineering: data/features.md
  - Machine Learning:
    - Classifier: ml/classifier.md
    - Unsupervised Learning: ml/unsupervised.md
    - Anomaly detection: anomaly.md
  - Deep Learning: 
    - Introduction: ml/deep-learning.md
    - Generative AI: ml/generative-ai.md
    - Prompt Engineering: ml/prompt-eng.md
  - Coding:
    - Getting started: coding/index.md
    - Pandas: coding/pandas.md
    - Scikit-learn: coding/sklearn.md
    - PyTorch: coding/pytorch.md
    - Data Visualization: coding/visualization.md
    - Kaggle: kaggle.md
    - LangChain: coding/langchain.md
    - Python studies:  https://jbcodeforce.github.io/python-code/
  - Techno:
    - Introduction: techno/index.md
    - Feature Store: techno/feature_store.md/
    - Key AI startups: techno/players_to_look.md
    - SageMaker: https://jbcodeforce.github.io/aws-studies/ai-ml/sagemaker
    - Streamlit: techno/streamlit.md
  - Solutions:
    - Introduction: solutions/index.md
  - Return to main: https://jbcodeforce.github.io

theme: 
  name: material
  logo: assets/logo.drawio.png
  favicon: assets/logo.drawio.png
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.tabs.sticky
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  #- bibtex:
  #    bib_file: "docs/refs.bib"
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true