site_name: Machine Learning Studies - Jerome Boyer
repo_url: https://github.com/jbcodeforce/ML-studies
site_url: https://jeromeboyer.net/ML-studies
copyright: Copyright &copy; 2018 - 2024 Jerome Boyer
nav:
  - About:
    - Introduction: index.md
    - Concepts: 
      - Core concepts: concepts/index.md
      - Math summary: concepts/maths.md
    - Data management:
      - Introduction: data/index.md
      - Feature Engineering: data/features.md
    - Methodology: methodology/index.md
  - Machine Learning:
    - Introduction: ml/index.md
    - Classifier: ml/classifier.md
    - Unsupervised Learning: ml/unsupervised.md
    - Anomaly detection: anomaly.md
    - Deep Learning: 
      - Introduction: ml/deep-learning.md
      - Distributed Data Parallel: coding/ddp.md
      - Neuro-Symbolic AI: neuro-symbolic/index.md
    - Generative AI: 
      - Introduction: genAI/index.md
      
      - Prompt Engineering: genAI/prompt-eng.md
      - Reference Architecture: genAI/ref-arch.md
      - RAG: genAI/rag.md
      - Anthropic: genAI/anthropic.md
  - Techno:
    - Coding getting started: coding/index.md
    - Data Visualization: coding/visualization.md
    - Feature Store: techno/feature_store.md/
    - Kaggle: kaggle.md
    - LangChain: coding/langchain.md
    - NiceGUI: techno/nicegui.md
    - Pandas: coding/pandas.md
    - Python studies:  https://jbcodeforce.github.io/python-code/
    - PyTorch: coding/pytorch.md
    - SageMaker: https://jbcodeforce.github.io/yarfba/ai-ml/sagemaker
    - Scikit-learn: coding/sklearn.md
    - Spark studies: https://jbcodeforce.github.io/spark-studies/
    - Streamlit: techno/streamlit.md
  - Solutions:
    - Introduction: solutions/index.md
    - Key AI startups: techno/players_to_look.md
  - Home: https://jbcodeforce.github.io

theme: 
  name: material
  logo: assets/logo.drawio.png
  favicon: assets/logo.drawio.png
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      #- navigation.expand
      - navigation.top
      - navigation.footer
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mermaid2
  #- bibtex:
  #    bib_file: "docs/refs.bib"
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/jbcodeforce'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jeromeboyer'
    - icon: fontawesome/solid/paper-plane
      mailto: jerome@intelligent-automations.com