site_name: Machine Learning Studies
repo_url: https://github.com/jbcodeforce/ml-basics
nav:
  - Introduction: index.md
  - Machine Learning:
    - Anomaly detection: anomaly.md
  - Compendium: compendium.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences