site_name: Machine Learning Studies
repo_url: https://github.com/jbcodeforce/ML-studies
nav:
  - Introduction: index.md
  - Math foundations: math.md
  - Data management:
    - Introduction: data/index.md
    - Feature Engineering: data/features.md
  - Machine Learning:
    - Classifier: ml/classifier.md
    - Unsupervised Learning: ml/unsupervised.md
    - Kaggle: kaggle.md
    - Anomaly detection: anomaly.md
  - Coding:
    - Environments: coding/index.md
    - Scikit-learn: coding/sklearn.md
    - Classifiers nb: notebooks/classifiers.ipynb
    - Python studies:  https://jbcodeforce.github.io/python-code/
  - Techno:
    - Introduction: techno/index.md
    - SageMaker: https://jbcodeforce.github.io/aws-studies/ai-ml/sagemaker
    - Generative AI: generativeAI/index.md
  - Return to main: https://jbcodeforce.github.io

theme: 
  name: material
  logo: assets/logo.drawio.png
  favicon: assets/logo.drawio.png
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.tabs.sticky
extra_css: ["extra.css"]
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
      execute: false
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true